name: release

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v4.3.0
        with:
          version: latest
      - uses: helm/chart-testing-action@v2.7.0
      - uses: helm/kind-action@v1.12.0
        with:
          node_image: kindest/node:v1.32.0
      - run: ct install --target-branch ${{ github.event.repository.default_branch }}

  release:
    name: Helm chart release
    runs-on: ubuntu-latest
    needs: [ 'lint-test' ]
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm & Add ArtifactHub file
        uses: azure/setup-helm@v4.3.0
        with:
          version: latest
        id: helm
      - run: |
          PAGES_BRANCH=gh-pages
          git clone "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" --branch $PAGES_BRANCH --single-branch .cr-release-packages
          
          # 在目标目录中创建 artifacthub-repo.yml 文件
          cat <<EOF > .cr-release-packages/artifacthub-repo.yml
          repositoryID: "b2c9fd9d-3383-4bb8-b8df-9e82e6a90e0c"
          owners:
            - name: "Redish101"
              email: "i@redish101.top"
          EOF
        shell: bash

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_existing: true
          mark_as_latest: true
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"