name: release

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v4.3.0
        with:
          version: latest
      - uses: helm/chart-testing-action@v2.7.0
      - uses: helm/kind-action@v1.12.0
        with:
          node_image: kindest/node:v1.32.0
      - run: ct install --target-branch ${{ github.event.repository.default_branch }}

  release:
    name: Helm chart release
    runs-on: ubuntu-latest
    needs: [ 'lint-test' ]
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: latest

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_existing: true
          mark_as_latest: true
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"